ModLoader.SetupFileHook( "lua/AlienTeam.lua", "lua/NS2_GorgeTunnel/AlienTeam.lua", "post" )
ModLoader.SetupFileHook( "lua/Balance.lua", "lua/NS2_GorgeTunnel/Balance.lua", "post" )
ModLoader.SetupFileHook( "lua/Crag.lua", "lua/NS2_GorgeTunnel/Crag.lua", "replace" )
ModLoader.SetupFileHook( "lua/Shade.lua", "lua/NS2_GorgeTunnel/Shade.lua", "replace" )
ModLoader.SetupFileHook( "lua/Shift.lua", "lua/NS2_GorgeTunnel/Shift.lua", "replace" )
ModLoader.SetupFileHook( "lua/GUIGorgeBuildMenu.lua", "lua/NS2_GorgeTunnel/GUIGorgeBuildMenu.lua", "replace" )
ModLoader.SetupFileHook( "lua/NS2Utility.lua", "lua/NS2_GorgeTunnel/NS2Utility.lua", "post" )
ModLoader.SetupFileHook( "lua/TechTreeConstants.lua", "lua/NS2_GorgeTunnel/TechTreeConstants.lua", "post" )
ModLoader.SetupFileHook( "lua/TechData.lua", "lua/NS2_GorgeTunnel/TechData.lua", "post" )
ModLoader.SetupFileHook( "lua/TechTreeButtons.lua", "lua/NS2_GorgeTunnel/TechTreeButtons.lua", "post" )
ModLoader.SetupFileHook( "lua/NetworkMessages.lua", "lua/NS2_GorgeTunnel/NetworkMessages.lua", "post" )
ModLoader.SetupFileHook( "lua/Tunnel.lua", "lua/NS2_GorgeTunnel/Tunnel.lua", "replace" )
ModLoader.SetupFileHook( "lua/TunnelEntrance.lua", "lua/NS2_GorgeTunnel/TunnelEntrance.lua", "replace" )
ModLoader.SetupFileHook( "lua/Weapons/Alien/DropStructureAbility.lua", "lua/NS2_GorgeTunnel/Weapons/Alien/DropStructureAbility.lua", "replace" )
ModLoader.SetupFileHook( "lua/Whip.lua", "lua/NS2_GorgeTunnel/Whip.lua", "replace" )

-- Allows Gorge Tunnel in Combat
ModLoader.SetupFileHook( "lua/Combat/Globals.lua", "lua/NS2_GorgeTunnel/BalanceCombat.lua", "post" )
